config/routes.rb
# == Route Map
#
#        Prefix Verb   URI Pattern                   Controller#Action
#       courses GET    /courses(.:format)            courses#index
#               POST   /courses(.:format)            courses#create
#    new_course GET    /courses/new(.:format)        courses#new
#   edit_course GET    /courses/:id/edit(.:format)   courses#edit
#        course GET    /courses/:id(.:format)        courses#show
#               PATCH  /courses/:id(.:format)        courses#update
#               PUT    /courses/:id(.:format)        courses#update
#               DELETE /courses/:id(.:format)        courses#destroy
#               POST   /users/:id/enroll(.:format)   users#enroll
#         users GET    /users(.:format)              users#index
#               POST   /users(.:format)              users#create
#      new_user GET    /users/new(.:format)          users#new
#     edit_user GET    /users/:id/edit(.:format)     users#edit
#          user GET    /users/:id(.:format)          users#show
#               PATCH  /users/:id(.:format)          users#update
#               PUT    /users/:id(.:format)          users#update
#               DELETE /users/:id(.:format)          users#destroy
#    instructor GET    /instructors/:id(.:format)    instructors#show
#     buildings GET    /buildings(.:format)          buildings#index
#               POST   /buildings(.:format)          buildings#create
#  new_building GET    /buildings/new(.:format)      buildings#new
# edit_building GET    /buildings/:id/edit(.:format) buildings#edit
#      building GET    /buildings/:id(.:format)      buildings#show
#               PATCH  /buildings/:id(.:format)      buildings#update
#               PUT    /buildings/:id(.:format)      buildings#update
#               DELETE /buildings/:id(.:format)      buildings#destroy
#         rooms GET    /rooms(.:format)              rooms#index
#               POST   /rooms(.:format)              rooms#create
#      new_room GET    /rooms/new(.:format)          rooms#new
#     edit_room GET    /rooms/:id/edit(.:format)     rooms#edit
#          room GET    /rooms/:id(.:format)          rooms#show
#               PATCH  /rooms/:id(.:format)          rooms#update
#               PUT    /rooms/:id(.:format)          rooms#update
#               DELETE /rooms/:id(.:format)          rooms#destroy
#   enrollments POST   /enrollments(.:format)        enrollments#create
#          root GET    /                             static_pages#home
#         login GET    /login(.:format)              sessions#new
#               POST   /login(.:format)              sessions#create
#        logout DELETE /logout(.:format)             sessions#destroy
#

Rails.application.routes.draw do
  
  resources :courses
  resources :sections
  resources :blocks
  
  post 'user_enroll' => 'users#enroll'
  resources :users
  
  resources :instructors, only: [:show]
  resources :buildings
  resources :rooms
  
  resources :enrollments, only: [:create, :destroy]
  delete 'remove_course' => 'enrollments#destroy'
  
  root 'static_pages#home'
  
  get 'login'   => 'sessions#new'
  post 'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  code            :integer
#  first_name      :string
#  last_name       :string
#  email           :string
#  password_digest :string
#  admin           :boolean          default(FALSE)
#  student         :boolean          default(FALSE)
#  employee        :boolean          default(FALSE)
#  instructor      :boolean          default(FALSE)
#  total_credits   :integer
#  gpa             :float
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  validates :last_name,  presence: true, length: { maximum: 50 }
  validates :code, uniqueness: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 },
                       allow_nil: true
                       
  has_many :enrollments
  has_many :sections, through: :enrollments
                       
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def interested_sections
    self.sections.where("status = ?", 1)
  end
  
  def wait_listed_sections
    self.sections.where("status = ?", 2)
  end
  
  def enrolled_sections
    self.sections.where("status = ?", 3)
  end
  
  private
  
    # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
    end
  
end

app/controllers/users_controller.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  code            :integer
#  first_name      :string
#  last_name       :string
#  email           :string
#  password_digest :string
#  admin           :boolean          default(FALSE)
#  student         :boolean          default(FALSE)
#  employee        :boolean          default(FALSE)
#  instructor      :boolean          default(FALSE)
#  total_credits   :integer
#  gpa             :float
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @interested_sections = @user.interested_sections
    @wait_listed_sections = @user.wait_listed_sections
    @enrolled_sections = @user.enrolled_sections
  end
  
  def enroll
    @user = User.find(session[:user_id])
    enrollments = @user.enrollments.where("status = ?", 1)
    
    enrollments.each do |e|
      if e.add_student_to_section
        e.update_attribute(:status, 3)
        flash[:success] = "Succesfully enrolled in courses."
      else
        e.update_attribute(:status, 2)
        flash[:warning] = "You have been wait-listed!"
      end
    end
    
    wait_listed_enrollments = @user.enrollments.where("status = ?", 2)
    
    wait_listed_enrollments.each do |w|
      section = w.section
      if section.enrollments < section.capacity
        w.update_attribute(:status, 3)
      end
    end

    redirect_back_or @user
  end
  
end

app/helpers/users_helper.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  code            :integer
#  first_name      :string
#  last_name       :string
#  email           :string
#  password_digest :string
#  admin           :boolean          default(FALSE)
#  student         :boolean          default(FALSE)
#  employee        :boolean          default(FALSE)
#  instructor      :boolean          default(FALSE)
#  total_credits   :integer
#  gpa             :float
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

module UsersHelper
  
  def user_schedule_html_class
    return "panel-collapse collapse in" if params[:date]
    return "panel-collapse collapse"
  end
end

app/views/users/show.html.erb
<% if @interested_sections.any? %>   
  <div class="panel-group user-cart">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2 class="panel-title">
          <a data-toggle="collapse" href="#collapse1">My Cart</a>
        </h2>
      </div>
      <div id="collapse1" class="panel-collapse collapse">
        <div class="panel-body">
          <% @interested_sections.each do |section| %>
            <% course = section.course %>
            <%= render partial: 'courses/course', locals: { course: course } %>
          <% end %>
        </div>
        <div class="panel-footer">
          <%= link_to "Enroll in courses", user_enroll_path, method: :post, class: "btn btn-md btn-primary" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<div class="panel-group user-courses">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h2 class="panel-title">
        <a data-toggle="collapse" href="#collapse2">My Courses</a>
      </h2>
    </div>
    
    <div id="collapse2" class="panel-collapse collapse">
      <div class="panel-body">
        <% @enrolled_sections.each do |section| %>
          <% course = section.course %>
          <%= render partial: 'courses/course', locals: { course: course } %>
        <% end %>
      </div>
      <div class="panel-footer">Panel Footer</div>
    </div>
  </div>
</div>

<div class="panel-group user-calendar">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h2 class="panel-title">
        <a data-toggle="collapse" href="#collapse3">My Schedule</a>
      </h2>
    </div>
    <div id="collapse3" class="<%= user_schedule_html_class %>">
      <div class="panel-body">
        <% blocks = Block.joins(:section => {:enrollments => :user}).where("user_id = ?", @user.id).all %>
        <%= render partial: 'shared/calendar', locals: { blocks: blocks } %>
      </div>
      <div class="panel-footer">Panel Footer</div>
    </div>
  </div>
</div>