config/routes.rb
# == Route Map
#
#        Prefix Verb   URI Pattern                   Controller#Action
#       courses GET    /courses(.:format)            courses#index
#               POST   /courses(.:format)            courses#create
#    new_course GET    /courses/new(.:format)        courses#new
#   edit_course GET    /courses/:id/edit(.:format)   courses#edit
#        course GET    /courses/:id(.:format)        courses#show
#               PATCH  /courses/:id(.:format)        courses#update
#               PUT    /courses/:id(.:format)        courses#update
#               DELETE /courses/:id(.:format)        courses#destroy
#               POST   /users/:id/enroll(.:format)   users#enroll
#         users GET    /users(.:format)              users#index
#               POST   /users(.:format)              users#create
#      new_user GET    /users/new(.:format)          users#new
#     edit_user GET    /users/:id/edit(.:format)     users#edit
#          user GET    /users/:id(.:format)          users#show
#               PATCH  /users/:id(.:format)          users#update
#               PUT    /users/:id(.:format)          users#update
#               DELETE /users/:id(.:format)          users#destroy
#    instructor GET    /instructors/:id(.:format)    instructors#show
#     buildings GET    /buildings(.:format)          buildings#index
#               POST   /buildings(.:format)          buildings#create
#  new_building GET    /buildings/new(.:format)      buildings#new
# edit_building GET    /buildings/:id/edit(.:format) buildings#edit
#      building GET    /buildings/:id(.:format)      buildings#show
#               PATCH  /buildings/:id(.:format)      buildings#update
#               PUT    /buildings/:id(.:format)      buildings#update
#               DELETE /buildings/:id(.:format)      buildings#destroy
#         rooms GET    /rooms(.:format)              rooms#index
#               POST   /rooms(.:format)              rooms#create
#      new_room GET    /rooms/new(.:format)          rooms#new
#     edit_room GET    /rooms/:id/edit(.:format)     rooms#edit
#          room GET    /rooms/:id(.:format)          rooms#show
#               PATCH  /rooms/:id(.:format)          rooms#update
#               PUT    /rooms/:id(.:format)          rooms#update
#               DELETE /rooms/:id(.:format)          rooms#destroy
#   enrollments POST   /enrollments(.:format)        enrollments#create
#          root GET    /                             static_pages#home
#         login GET    /login(.:format)              sessions#new
#               POST   /login(.:format)              sessions#create
#        logout DELETE /logout(.:format)             sessions#destroy
#

Rails.application.routes.draw do
  
  resources :courses
  resources :sections
  resources :blocks
  
  post 'user_enroll' => 'users#enroll'
  resources :users
  
  resources :instructors, only: [:show]
  resources :buildings
  resources :rooms
  
  resources :enrollments, only: [:create, :destroy]
  delete 'remove_course' => 'enrollments#destroy'
  
  root 'static_pages#home'
  
  get 'login'   => 'sessions#new'
  post 'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
end

app/views/shared/_admin_tools.html.erb
<li><strong>Admin toolbar</strong></li>
<li><%= link_to "Users", users_path %></li>
<li><%= link_to "Courses", courses_path %></li>
<li><%= link_to "Sections", '#' %></li>
<li><%= link_to "Blocks", '#' %></li>
<li><%= link_to "Buildings", buildings_path %></li>
<li><%= link_to "Rooms", rooms_path %></li>

app/views/shared/_calendar.html.erb
<div class="calendar">
  
  <h5>
    <%= link_to "[< Previous Week]", url_for(params.merge(date: (starting_date - 7).strftime("%F"))) %>
    
     | Start Time: 
    <%= link_to "6:00", url_for(params.merge(start_time: 6)) %>
    <%= link_to "7:00", url_for(params.merge(start_time: 7)) %>
    <%= link_to "8:00", url_for(params.merge(start_time: 8)) %>
    <%= link_to "9:00", url_for(params.merge(start_time: 9)) %>

    | End Time: 
    <%= link_to "20:00", url_for(params.merge(end_time: 20)) %>
    <%= link_to "21:00", url_for(params.merge(end_time: 21)) %>
    <%= link_to "22:00", url_for(params.merge(end_time: 22)) %>
    <%= link_to "23:00", url_for(params.merge(end_time: 23)) %>
    
    | <%= link_to "Show Weekend", url_for(params.merge(weekend: "t")) %>
    | <%= link_to "Hide Weekend", url_for(params.merge(weekend: "f")) %>
    
    | <%= link_to "[Next Week >]", url_for(params.merge(date: (starting_date + 7).strftime("%F"))) %>
  </h5>
  
  <% start_time = params[:start_time] || 7 %>
  <% start_time = start_time.to_i %>
  <% start_time = 7 if (start_time < 0) or (start_time > 12) %>
  
  <% end_time = params[:end_time] || 21 %>
  <% end_time = end_time.to_i %>
  <% end_time = 21 if (end_time < 18) or (end_time > 23) %>
  
  <% weekend = params[:weekend] || "t" %>
  
  <table class="table table-bordered table-striped table-hover">
    <thead>
      <tr>
        <th><!-- blank cell --></th>
        <% (0..6).to_a.each do |count| %>
          <% if (weekend == "f") and ((count == 0) or (count == 6)) %>
            <th width="0%"></th>
          <% else %>
            <% date = starting_date + count.day %>
            <th width="13%"><%= date.strftime("%a") %><br><%= date.strftime("%F") %></th>
          <% end %>
        <% end %>
      </tr>
    </thead>
    
    <tbody>
      <% (start_time..end_time).to_a.each do |hour| %>
        <tr>
          <% time = Time.at(hour*3600).strftime("%I:%M %p") %>
          <td width="9%" class="schedule-row">
            <div>
              <strong><%= time %></strong>
            </div>
          </td>
          
          <% (0..6).to_a.each do |count| %>
            <% if (weekend == "f") and ((count == 0) or (count == 6)) %>
              <td width="0%"></td>
            <% else %>
              <td width="13%">
                <% blocks.each do |b| %>
                  <% date = starting_date + count.day %>
                  <% if b.is_scheduled(date, hour) %>
                    <p>
                      <%= b.section.course.abbr %><br>
                      <%= b.time_range %>
                    </p>
                  <% end %> 
                <% end %>
              </td>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
    
  </table>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-default">
  <div class="container-fluid">
    
    <div class="navbar-header">
      <ul class="nav navbar-header navbar-left">
        <li><%= link_to image_tag("cat-icon.png", width: 50, height: 50, 
            alt: "Felix logo"), root_path %></li>
      </ul>
    </div>
    
    <div>
    <ul class="nav navbar-nav navbar-left">
          <% if logged_in? %>
            <li><%= link_to "[ #{@current_user.first_name} #{@current_user.last_name} ]", @current_user %></li>
          <% end %>
      </ul>
    </div>
    
    <div>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in_user_is_admin? %>
          <%= render 'shared/admin_tools' %>
        <% end %>

        <% if logged_in? %>
          <li><%= link_to "Course Catalog", courses_path %></li>
          <li><%= link_to "Log Out", logout_path, method: "delete" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>