config/routes.rb
# == Route Map
#
#        Prefix Verb   URI Pattern                   Controller#Action
#       courses GET    /courses(.:format)            courses#index
#               POST   /courses(.:format)            courses#create
#    new_course GET    /courses/new(.:format)        courses#new
#   edit_course GET    /courses/:id/edit(.:format)   courses#edit
#        course GET    /courses/:id(.:format)        courses#show
#               PATCH  /courses/:id(.:format)        courses#update
#               PUT    /courses/:id(.:format)        courses#update
#               DELETE /courses/:id(.:format)        courses#destroy
#               POST   /users/:id/enroll(.:format)   users#enroll
#         users GET    /users(.:format)              users#index
#               POST   /users(.:format)              users#create
#      new_user GET    /users/new(.:format)          users#new
#     edit_user GET    /users/:id/edit(.:format)     users#edit
#          user GET    /users/:id(.:format)          users#show
#               PATCH  /users/:id(.:format)          users#update
#               PUT    /users/:id(.:format)          users#update
#               DELETE /users/:id(.:format)          users#destroy
#    instructor GET    /instructors/:id(.:format)    instructors#show
#     buildings GET    /buildings(.:format)          buildings#index
#               POST   /buildings(.:format)          buildings#create
#  new_building GET    /buildings/new(.:format)      buildings#new
# edit_building GET    /buildings/:id/edit(.:format) buildings#edit
#      building GET    /buildings/:id(.:format)      buildings#show
#               PATCH  /buildings/:id(.:format)      buildings#update
#               PUT    /buildings/:id(.:format)      buildings#update
#               DELETE /buildings/:id(.:format)      buildings#destroy
#         rooms GET    /rooms(.:format)              rooms#index
#               POST   /rooms(.:format)              rooms#create
#      new_room GET    /rooms/new(.:format)          rooms#new
#     edit_room GET    /rooms/:id/edit(.:format)     rooms#edit
#          room GET    /rooms/:id(.:format)          rooms#show
#               PATCH  /rooms/:id(.:format)          rooms#update
#               PUT    /rooms/:id(.:format)          rooms#update
#               DELETE /rooms/:id(.:format)          rooms#destroy
#   enrollments POST   /enrollments(.:format)        enrollments#create
#          root GET    /                             static_pages#home
#         login GET    /login(.:format)              sessions#new
#               POST   /login(.:format)              sessions#create
#        logout DELETE /logout(.:format)             sessions#destroy
#

Rails.application.routes.draw do
  
  resources :courses
  resources :sections
  resources :blocks
  
  post 'user_enroll' => 'users#enroll'
  resources :users
  
  resources :instructors, only: [:show]
  resources :buildings
  resources :rooms
  
  resources :enrollments, only: [:create, :destroy]
  delete 'remove_course' => 'enrollments#destroy'
  
  root 'static_pages#home'
  
  get 'login'   => 'sessions#new'
  post 'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
end

app/models/section.rb
# == Schema Information
#
# Table name: sections
#
#  id                  :integer          not null, primary key
#  course_id           :integer
#  instructor_id       :integer
#  code                :integer
#  capacity            :integer
#  enrolled            :integer
#  wait_listed         :integer
#  open_for_enrollment :boolean          default(FALSE)
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  number              :integer
#  semester            :string
#

class Section < ActiveRecord::Base
  belongs_to :course
  belongs_to :instructor
  
  has_many   :blocks
  has_many   :enrollments
  
  has_many   :students, through: :enrollments, source: :users
  
  validates :course_id, presence: true
  validates :instructor_id, presence: true
  
  def block_start_dates
    string = String.new
    self.blocks.each do |block|
      string += block.start_date.to_s
      string += "<br>"
    end
    return string.html_safe
  end
  
  def block_end_dates
    string = String.new
    self.blocks.each do |block|
      string += block.end_date.to_s
      string += "<br>"
    end
    return string.html_safe
  end
  
  def block_days
    string = String.new
    
    self.blocks.each do |block|
      string += block.days
      string += "<br>"
    end
    return string.html_safe
  end
  
  def block_time_ranges
    string = String.new
    self.blocks.each do |block|
      if (block.start_time == "00:00") and (block.end_time == "00:00")
        string += "Hours Arranged"
        string += "<br>"
      else
        string += block.start_time.to_time.strftime("%I:%M %P")
        string += "-"
        string += block.end_time.to_time.strftime("%I:%M %P")
        string += "<br>"
      end
    end
    return string.html_safe
  end
  
  def block_locations
    string = String.new
    self.blocks.each do |block|
      string += CGI::escapeHTML(block.location)
      string += "<br>"
    end
    return string.html_safe
  end
  
  def padded_code
    code.to_s.rjust(2, '0')
  end
end

app/views/sections/_section.html.erb
<tr>
  <td>
    <% if logged_in_user_is_student? and current_page?(controller: 'courses', action: 'index') %>
      <%= link_to "Add", enrollments_path(section: section.id), method: :post, class: "btn btn-xs btn-primary" %>
    <% elsif params[:controller] == 'users' %>
      <%= link_to "Delete", remove_course_path(section: section.id), 
          method: :delete, class: "btn btn-xs btn-primary" %>
    <% end %>
  </td>
  <td><%= section.padded_code %></td>
  <td><%= link_to_instructor(section) %></td>
  <td><%= section.course.credits %></td>
  <td><%= section.capacity %></td>
  <td><%= section.enrolled %></td>
  <td><%= section.wait_listed %></td>
  <td>
    <p class="model-block-line"><%= section.block_start_dates %></p>
  </td>
  <td>
    <p class="model-block-line"><%= section.block_end_dates %></p>
  </td>
  <td>
    <p class="model-block-line"><%= section.block_days %></p>
  </td>
  <td>
    <p class="model-block-line"><%= section.block_time_ranges %></p>
  </td>
  <td>
    <p class="model-block-line"><%= section.block_locations %></p>
  </td>
</tr>
  

app/views/sections/_section_header.html.erb
<tr>
  <th><!-- empty cell --></th>
  <th>Section</th>
  <th>Instructor</th>
  <th>Cred</th>
  <th>Cap</th>
  <th>Enr</th>
  <th>Wait</th>
  <th>Start Date</th>
  <th>End Date</th>
  <th>Day</th>
  <th>Time</th>
  <th>Location</th>
</tr>