config/routes.rb
# == Route Map
#
#        Prefix Verb   URI Pattern                   Controller#Action
#       courses GET    /courses(.:format)            courses#index
#               POST   /courses(.:format)            courses#create
#    new_course GET    /courses/new(.:format)        courses#new
#   edit_course GET    /courses/:id/edit(.:format)   courses#edit
#        course GET    /courses/:id(.:format)        courses#show
#               PATCH  /courses/:id(.:format)        courses#update
#               PUT    /courses/:id(.:format)        courses#update
#               DELETE /courses/:id(.:format)        courses#destroy
#               POST   /users/:id/enroll(.:format)   users#enroll
#         users GET    /users(.:format)              users#index
#               POST   /users(.:format)              users#create
#      new_user GET    /users/new(.:format)          users#new
#     edit_user GET    /users/:id/edit(.:format)     users#edit
#          user GET    /users/:id(.:format)          users#show
#               PATCH  /users/:id(.:format)          users#update
#               PUT    /users/:id(.:format)          users#update
#               DELETE /users/:id(.:format)          users#destroy
#    instructor GET    /instructors/:id(.:format)    instructors#show
#     buildings GET    /buildings(.:format)          buildings#index
#               POST   /buildings(.:format)          buildings#create
#  new_building GET    /buildings/new(.:format)      buildings#new
# edit_building GET    /buildings/:id/edit(.:format) buildings#edit
#      building GET    /buildings/:id(.:format)      buildings#show
#               PATCH  /buildings/:id(.:format)      buildings#update
#               PUT    /buildings/:id(.:format)      buildings#update
#               DELETE /buildings/:id(.:format)      buildings#destroy
#         rooms GET    /rooms(.:format)              rooms#index
#               POST   /rooms(.:format)              rooms#create
#      new_room GET    /rooms/new(.:format)          rooms#new
#     edit_room GET    /rooms/:id/edit(.:format)     rooms#edit
#          room GET    /rooms/:id(.:format)          rooms#show
#               PATCH  /rooms/:id(.:format)          rooms#update
#               PUT    /rooms/:id(.:format)          rooms#update
#               DELETE /rooms/:id(.:format)          rooms#destroy
#   enrollments POST   /enrollments(.:format)        enrollments#create
#          root GET    /                             static_pages#home
#         login GET    /login(.:format)              sessions#new
#               POST   /login(.:format)              sessions#create
#        logout DELETE /logout(.:format)             sessions#destroy
#

Rails.application.routes.draw do
  
  resources :courses
  resources :sections
  resources :blocks
  
  post 'user_enroll' => 'users#enroll'
  resources :users
  
  resources :instructors, only: [:show]
  resources :buildings
  resources :rooms
  
  resources :enrollments, only: [:create, :destroy]
  delete 'remove_course' => 'enrollments#destroy'
  
  root 'static_pages#home'
  
  get 'login'   => 'sessions#new'
  post 'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
end

app/controllers/courses_controller.rb
# == Schema Information
#
# Table name: courses
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  prefix      :string
#  code        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  credits     :integer
#

class CoursesController < ApplicationController
  before_action :admin_user, only: [:edit, :update, :destroy, :new, :create]
  
  def index
    @courses = Course.search(params[:search]).order(:prefix).order(:code)
  end
  
  def new
    @course = Course.new
  end
  
  def create
    @course = Course.new(course_params)
    if @course.save
      flash[:success] = "Course created."
      redirect_to root_url
    else
      render 'new'
    end
  end
  
  def edit
    @course = Course.find(params[:id])
  end
  
  def update
    @course = Course.find(params[:id])
    if @course.update_attributes(course_params)
      flash[:success] = "Course updated."
      redirect_to @course
    else
      render 'edit'
    end
  end
  
  def show
    @course = Course.find(params[:id])
  end
  
  private
  
    def course_params
      params.require(:course).permit(:name, :prefix, :code, :description, :credits)
    end
    
    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless logged_in_user_is_admin?
    end
end

app/helpers/courses_helper.rb
# == Schema Information
#
# Table name: courses
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  prefix      :string
#  code        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  credits     :integer
#

module CoursesHelper
    def status_icon(course)
      return nil if params[:controller] != "users"
      
      course.sections.each do |section|
        if e = Enrollment.find_by(user_id: @user.id, section_id: section.id)
          return image_tag("check-icon.png", width: 20, height: 20, title: "Completed") if e.status == 4
          return image_tag("student-icon.png", width: 20, height: 20, title: "Enrolled") if e.status == 3
          return image_tag("warning-icon.png", width: 20, height: 20, title: "Wait-listed") if e.status == 2
        end
      end
      
      nil
      
    end
end

app/views/courses/_course.html.erb
<div class="empty-space">
  <h3><!-- empty line --></h3>
</div>

<div class="model-course">
  <h3>
    <%= link_to "[Edit]", edit_course_path(course) if logged_in_user_is_admin? and params[:controller] == "courses" %>
    <%= status_icon(course) %> <strong><%= course.abbr %></strong>
    <%= " | " + course.name if !course.name.nil? %>
  </h3>
  <p><%= course.description %></p>
    
  <% if course.sections.any? %>
    <table class="table table-striped">
      <%= render 'sections/section_header' %>
    
      <% course.sections.each do |section| %>
        <% if params[:controller] == "users" %>
          <%= render section if Enrollment.exists?( { user_id: @user.id, section_id: section.id } ) %>
        <% else %>
          <%= render section %>
        <% end %>
      <% end %>
    </table>
  <% end %>
</div>

app/views/courses/edit.html.erb
<h1>Edit Course</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3 form-horizontal">
    <%= form_for(@course) do |f1| %>
    
      <%= render 'shared/error_messages', object: f1.object %>
    
      <div class="form-group">
        <div class="col-sm-9">
          <div class="input-group">
            <span class="input-group-addon">
              <%= f1.label :name %>
            </span>
            <%= f1.text_field :name, class: 'form-control' %>
          </div>
        </div>
      </div>
      
      <div class="form-group form-inline">
        <div class="col-sm-9">
          <div class="input-group">
            <span class="input-group-addon">
              <%= f1.label "Catalog Number" %>
            </span>
            <%= f1.text_field :prefix, class: 'form-control', size: 6 %>
            <%= f1.text_field :code, class: 'form-control', size: 6 %>
          </div>
        </div>
        
        <div class="form-group form-inline">
          <div class="col-sm-9">
            <div class="input-group">
              <span class="input-group-addon">
                <%= f1.label :credits %>
              </span>
              <%= f1.text_field :credits, class: 'form-control', size: 6 %>
            </div>
          </div>
        </div>
      </div>
      
      <div class="form-group">
        <%= f1.label :description %>
        <%= f1.text_area :description, class: 'form-control', rows: 6 %>
      </div>
      
      <div class="form-group">
        <% sections = Section.where("course_id = ?", params[:id]) %>
        <h3><%= f1.label :sections %></h3>
          <% sections.each do |section| %>
            <div class="panel panel-default">
              <%= fields_for(section) do |f2| %>
                <div class="panel-heading form-inline">
                  <%= f2.label :code %>
                  <%= f2.text_field :code, class: 'form-control', value: section.padded_code %>
                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                  <%= f2.label :instructor %>
                  <%= f2.collection_select :instructor_id, Instructor.all, :id, :last_name, prompt: true %>
                </div>
                
                <div class="panel-body">
                  <% blocks = Block.where("section_id = ?", section.id) %>
                  <% blocks.each do |block| %>
                    <%= fields_for(block) do |f3| %>
                    
                      <div class="form-group form-inline">
                        <%= f3.label :start_date %>
                        <%= f3.date_select :start_date, class: 'form-control' %>
                      </div>
                      <div class="form-group form-inline">
                        <%= f3.label :end_date %>
                        <%= f3.date_select :end_date, class: 'form-control' %>
                      </div>
                      
                      <div class="form-group form-inline">
                        <%= f3.label :start_time %>
                        <%= f3.time_select :start_time, class: 'form-control' %>
                      </div>
                        
                      <div class="form-group form-inline">
                        <%= f3.label :end_time %>
                        <%= f3.time_select :end_time, class: 'form-control' %>
                      </div>
                      
                      <div class="form-group form-inline">
                        [<%= f3.label :monday %>
                        <%= f3.check_box :monday, class: 'form-control' %>]
                        
                        [<%= f3.label :tuesday %>
                        <%= f3.check_box :tuesday, class: 'form-control' %>]
                        
                        [<%= f3.label :wednesday %>
                        <%= f3.check_box :wednesday, class: 'form-control' %>]
                        
                        [<%= f3.label :thursday %>
                        <%= f3.check_box :thursday, class: 'form-control' %>]
                        
                        [<%= f3.label :friday %>
                        <%= f3.check_box :friday, class: 'form-control' %>]
                        
                        [<%= f3.label :saturday %>
                        <%= f3.check_box :saturday, class: 'form-control' %>]
                        
                        [<%= f3.label :sunday %>
                        <%= f3.check_box :sunday, class: 'form-control' %>]
                      </div>
                    <% end %>
                  <% end %>
                </div>
              </div>
            <% end %>
          <% end %>
      </div>

      <%= f1.submit "Update course", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/courses/index.html.erb
<h1>Courses</h1>

<div class="search1">
  <%= form_tag(courses_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Courses" %>
  <%= submit_tag "Search" %>
  <% end %>
</div>

<div class="model-courses">
    <%= render @courses %>
</div>

app/views/courses/new.html.erb
<h1>New Course</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@course) do |f| %>
    
      <%= render 'shared/error_messages', object: f.object %>
    
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>

      <%= f.label :prefix %>
      <%= f.text_field :prefix, class: 'form-control' %>

      <%= f.label :code %>
      <%= f.text_field :code, class: 'form-control' %>
      
      <%= f.label :credits %>
      <%= f.text_field :credits, class: 'form-control' %>

      <%= f.submit "Create course", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/courses/show.html.erb
<%= render partial: @course, locals: { course: @course } %>